name: Push stack to heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY }}
          heroku_app_name: "api-pi-henry-jtovarto"
          heroku_email: ${{secrets.HEROKU_API_KEY }}
        env:
          HD_APP_BASE: "api"
  client_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY }}
          heroku_app_name: "client-pi-henry-jtovarto"
          heroku_email: ${{secrets.HEROKU_API_KEY }}
        env:
          HD_APP_BASE: "client"
          HD_REACT_APP_API_URL: "https://api-pi-henry-jtovarto.herokuapp.com"
